### ISSUE TITLE
Getting error: Will not attempt to authenticate using SASL (unknown error)

### ISSUE THREAD

**Issue by cfmagnum** [cf-platform-eng/kafka-service-broker#2]
I followed the steps as given an readme page. I deployed the kafka service broker.

But while creating the service instance it get's failed. When I checked the logs, it's showing following error:

Will not attempt to authenticate using SASL (unknown error)

Please help me to fix this.

**Comment by JaredGordon** [comment]
Hi cfmagnum. based on similar issues, this might be a firewall/connectivity problem. See here for example: https://github.com/wurstmeister/kafka-docker/issues/47. Have you taken a look to see that your kafka nodes can speak to your zookeeper nodes?

**Comment by JaredGordon** [comment]
closing this for now, we can re-open if it becomes active again.
